### ISSUE TITLE
FEATURE REQUEST Allow docker commands to run within a toast task

### ISSUE THREAD

**Issue by bobhenkel** [stepchowfun/toast#225]
It would be nice if a user could run docker commands from the tasks in toast.

Specific commands like:

```
docker build
docker run
```

To do this you may need to add a switch to toast to allow privileged mode and to mount the docker sock file.

**Comment by stepchowfun** [comment]
I keep going back and forth on this one.

An alternative I'm considering is to just support tasks that run on the host machine rather than inside the container. That would be useful in a variety of situations (including yours, I presume). For example, to produce precompiled macOS binaries for new Toast releases, I currently have to run a script on my MacBook. But if we had that, it could just be a Toast task.

These host-side tasks wouldn't be portable, but maybe that's okay as long as we're explicit about that.

**Comment by stepchowfun** [comment]
Fixed in v0.29.0. See https://github.com/stepchowfun/toast/pull/268 for an example.
