### ISSUE TITLE
output_paths doesn't work with tmpfs

### ISSUE THREAD

**Issue by kbknapp** [stepchowfun/toast#239]
First, thank you for `toast` I love it!

**Description**

When `/tmp` is mounted as `tmpfs` (which is the default for certain major Linux distributions [such as Fedora]), using `output_paths` will fail with an error:

```
[ERROR] Unable to move file /tmp/.tmpFH7oiU/data to destination /home/foo/bar/baz. Reason: Invalid cross-device link (os error 18)
```

**Instructions to reproduce the bug**

* Mount `/tmp` as `tmpfs`
* Run any toastfile with an `output_paths`

**System information:**
 - OS: Fedora 30
 - Docker version: Docker version 18.06.3, build d7080c1
 - Toast version: Toast 0.21.0

**Additional context**

From the `docker cp` help page:

```
It is not possible to copy certain system files such as resources under /proc, /sys, /dev,
tmpfs, and mounts created by the user in the container.  However, you can still copy such
files by manually running tar in docker exec.  For example (consider SRC_PATH and
DEST_PATH are directories):

    $ docker exec foo tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | tar Cxf DEST_PATH -

or

    $ tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | docker exec -i foo tar Cxf DEST_PATH -
```

**Comment by stepchowfun** [comment]
Hi @kbknapp, thanks for the bug report! This one is a bummer because it's an issue with Docker. I am quite hesitant to use that workaround for two reasons:

1) It's not great for Toast to assume `tar` exists in the container. Toast currently only assumes `/bin/su` exists (for running commands as the appropriate user with their preferred shell), which is already more than I'd like.
2) `docker exec` only works for running containers. By the time we're copying the `output_paths` to the host, the container has already stopped. So we'd have to (a) restart the container, (b) give it some way to stay running without actually doing anything, (c) run that `docker exec` command, and then (d) stop the container again. This would introduce extra latency, I don't know how to do (b) in a portable way.

I'm open to ideas! But sadly right now I don't see a nice way around this.

cc @juliahw in case she has any ideas too

**Comment by stepchowfun** [comment]
Actually, you know what, based on the error message you gave, I don't think this is related to that Docker bug at all. I think the error happens here:

https://github.com/stepchowfun/toast/blob/2110db07acffe4f14f148949b55ab6836df08cf2/src/docker.rs#L255-L260

At this point, Toast has already copied the file to a temporary directory, and it's now trying to move the file to the destination. Apparently renaming a file in Unix doesn't seem to work across these two filesystems (tempfs and non-tempfs), which makes sense now that I think about it.

@kbknapp Can you confirm this hypothesis by `mv`ing a file from `/tmp` to, say, your home directory?

If so, I think we can work around this by first trying the rename, and then trying a copy if the rename fails.

**Comment by stepchowfun** [comment]
The bug should be fixed now due to https://github.com/stepchowfun/toast/pull/240, so I'll close this issue now. @kbknapp would you like to reinstall and confirm that it's fixed for you?

**Comment by kbknapp** [comment]
It's fixed! Thanks for the super quick response :+1:
