### ISSUE TITLE
FEATURE REQUEST Windows support

### ISSUE THREAD

**Issue by alex-kattathra-johnson** [stepchowfun/toast#262]
**Description**
A clear description of what you want to happen.
One of the benefits of containerization of dev envs is being able to run them in a platform agnostic way, so it'd be cool if toast could run on Windows

**Alternatives considered**
A clear description of any alternative solutions or features you've considered.

**Additional context**
Add any other context about the feature request here.
I'd love to help make this happen.

**Comment by stepchowfun** [comment]
Windows support would be great! I believe it should be very doable. Are you up for tackling this? I don't have a Windows machine, and that's the only reason I haven't supported Windows thus far.

**Comment by TheOriginalAlex** [comment]
@stepchowfun: I do have a Windows computer and I would love to give it a shot.  Thanks!

**Comment by stepchowfun** [comment]
Sounds great! Most of the code is platform-independent, so I expect there shouldn't be too much work involved. One thing that comes to mind is the usage of [`is_absolute`](https://doc.rust-lang.org/std/path/struct.Path.html#method.is_absolute), which has different behavior on Windows and Unix.

Just clarifying: when we talk about Windows support, we're talking about running Linux containers on Windows (as opposed to Windows containers on Windows), right?

**Comment by TheOriginalAlex** [comment]
Correct!

**Comment by stepchowfun** [comment]
@TheOriginalAlex Have you had a chance to look into Windows support? Not urgent of course.

**Comment by TheOriginalAlex** [comment]
@stepchowfun: Sorry, haven't had a chance to look into it yet.  Will start on it this weekend.

**Comment by xmclark** [comment]
I discovered Toast this weekend and am pretty jazzed about it. I saw that windows-support was in-flight, so I helped with the rebase and tidying in #306 . I also added a simple CI pipeline to be foundation for release confidence to windows. @stepchowfun @qthree could you add a review? Thanks!

**Comment by xmclark** [comment]
I'm guessing that travis-ci webhook is still set in this project, and that's why I can't get a green check on my PR 🟡 😭 .

**Comment by stepchowfun** [comment]
That's great!! I promise to take a look within the next 7 days. (I wish I could give you a faster turnaround time, but I'm just too busy.)

That Travis check is weird; we haven't been using Travis since March. I double checked that Travis is not configured as a required status check:

![Screen Shot 2020-08-03 at 5 47 23 PM](https://user-images.githubusercontent.com/796574/89240787-013ea880-d5b2-11ea-902c-4d08b7990855.png)

I did see that the Travis webhook was still configured for some reason, so I just deleted that. Could you try pushing a new commit (or amending the last commit)?

**Comment by xmclark** [comment]
I think that last `ci` checkbox is travis. I force pushed a new commit with an altered message and I still see that opaque ci check (that never finishes).

**Comment by stepchowfun** [comment]
So from looking at [a random PR](https://github.com/stepchowfun/toast/pull/304) from the recent past, it looks like `ci` corresponds to the GitHub actions: 

![Screen Shot 2020-08-03 at 6 48 24 PM](https://user-images.githubusercontent.com/796574/89243876-eec86d00-d5b9-11ea-8b02-85e40e4b4553.png)

In that screenshot, I hovered over one of them so we can see the URL that it points to in the tooltip at the bottom.

I think the reason the check doesn't pass on your PR is because you changed the `name` of the action(s), and GitHub apparently uses that name for the status check. That's OK, I can still review it in this state, and then I can update the required status check settings accordingly when we're ready to merge the PR.

**Comment by xmclark** [comment]
That makes perfect sense. I imagine you may have some input on the sames of these build steps. Looking forward to feedback!

**Comment by stepchowfun** [comment]
Thanks to @xmclark's contribution, the code has now been updated to support Windows as of v0.32.0. However, I don't have a release process for Windows, so Windows users will need to build Toast themselves (e.g., with `cargo install toast`). Also, no stability guarantees are made for Windows (but bugfixes are welcome).
