### ISSUE TITLE
ssh agent forwarding

### ISSUE THREAD

**Issue by meantheory** [stepchowfun/toast#295]
**Description**
Access private repositories via ssh by utilizing ssh agent forwarding. This would prevent the need to share this kind of secret with toast. This feature has been implemented in docker with buildkit and is described in the following article.

https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066

**Alternatives considered**
I'd be open to any alternatives that negate the need to copy a private key into a docker image that is ultimately cached.

**Additional context**
This is primarily a security feature for organizations that depend heavily on ssh during builds.

**Comment by stepchowfun** [comment]
Hi @meantheory! Thanks for submitting this feature request. I will have to look into this more. At first glance, this might be difficult because this appears to be a feature exposed from `docker build`, but Toast does not use `docker build` (it uses `docker container create` + `docker container cp` + `docker container start` + `docker container commit` + `docker container rm`).

In the meantime, one idea is to mount the SSH key as a volume (using the `mount_paths` option in your toastfile). This of course relies on being able to trust the code running inside the container not to copy the key to the layered filesystem, so it's not ideal.

Another not-so-ideal solution (which can be combined with the first no-so-ideal solution) is to disable caching for the tasks that use secrets.

I understand the need for this feature and will think about it more.

**Comment by meantheory** [comment]
hmm, my apologies - it didn't occur to me how much docker you were reusing under the toast hood. I know the following works fine when running containers outside a build.

    docker run -i -t -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent ubuntu /bin/bash

a [variant of this approach works on docker for mac](https://github.com/docker/for-mac/issues/410#issuecomment-577064671). so, seems like a completely workable solution to me. i will close this feature request. Thanks!
