### ISSUE TITLE
Use toast for multi stage image creation with remote cache

### ISSUE THREAD

**Issue by cemoktra** [stepchowfun/toast#359]
**Description**
Is it possible to create a named image of a task result?

**Comment by stepchowfun** [comment]
Hi @cemoktra, Toast does not currently support that directly (see the discussion [here](https://github.com/stepchowfun/toast/issues/318)), but you can install the Docker CLI in a Toast task and run Docker commands to build images on the host (see [this](https://github.com/stepchowfun/toast/pull/268) for details).

This has feature been requested before, but I think this request can arise from a misunderstanding of Toast. The images that Toast builds are the cumulative result of running the task and all its dependencies, which typically includes installing things like system packages, development tools, etc. Those images are not very useful other than for caching Toast tasks, since they are usually too bloated for production use.

However, if you have a different use case in mind, I'd love to discuss it here.

**Comment by cemoktra** [comment]
Well for me it would be kind of doing the same thing as in a dockerfile now. But with different or new or rusty tooling.
In the end I would be compiling some packages and use this task as a base for different repositories. 

Or maybe asking in a way like support including common toast files which will then use the same remote cache

**Comment by stepchowfun** [comment]
Thanks for the context. I'm not sure that Toast would be an improvement over a plain Dockerfile for that use case. Or do you mean the advantage of using Toast for that purpose would be its remote caching functionality?

**Comment by cemoktra** [comment]
Yes remote caching and yml syntax.

**Comment by stepchowfun** [comment]
Hi @cemoktra, thanks for clarifying. I apologize for closing this issue prematurely.

However, I am concerned that your use case (building Docker base images) is not what Toast was designed for, and adding this feature would only be the first step to making toastfiles a general purpose replacement for Dockerfiles. For example, Toast currently offers no way to set the entrypoint, do multi-stage builds, etc. All of those features would make Toast more complicated and also potentially constrain the ways in which Toast uses Docker images for caching.

My personal preference would be to keep Toast focused on doing one thing well: running tasks in containerized environment. I still welcome any further discussion, but I thought it would be best to let you know how I'm thinking about this.

**Comment by cemoktra** [comment]
Okay.
